### Spring Boot configuration
server:
  port: 8787
  compression:
    enabled: true
    mime-types: text/csv
  servlet:
    context-path: /users

management:
  server:
    port: 8081
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    status:
      order: FATAL, OUT_OF_SERVICE, DOWN, UNKNOWN, KAFKA_ISSUE, INTERNAL_SERVICE_ISSUE, UP , FINE
      http-mapping:
        FATAL: 509
        KAFKA_ISSUE: 503
        INTERNAL_SERVICE_ISSUE: 201
        FINE: 510
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /
      exposure:
        include: ping, internal, prometheus, metrics, loggers

spring:
  datasource:
    url: jdbc:mysql://${Values.global.db.user.host}:${Values.global.db.user.port}/${Values.global.db.user.database}?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ${Values.global.secret.db.user.username}
    password: ${Values.global.secret.db.user.password}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      primary-dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
        order_inserts: true
        order_updates: true
        format_sql: false
        jdbc:
          batch_versioned_data: true
          batch_size: 1000
          lob.non_contextual_creation: true

  logging:
    config: classpath:logback.xml
    level:
      root: INFO
      org:
        springframework: INFO
      com.ayla.user: INFO